### ISSUE TITLE
Running tests in the browser

### ISSUE THREAD

**Issue by varungupta85** [robertknight/react-testing#2]
How do I run the tests in the browser? I am trying to run the tests in windows. I was able to run webpack after a few modifications. Mainly, I was getting some module not found errors in jsdom and node-fetch and had to add them ignore plugin. When I hit http://localhost:8080/webpack-dev-server/tests.html , it just says App is ready. When I run http://localhost:8080/webpack-dev-server/tests.bundle.js which is what I see in the video, I see the js file in the browser.

Could you please tell me how do I run these tests in the browser the way you have shown in the video?

**Comment by robertknight** [comment]
> Mainly, I was getting some module not found errors in jsdom and node-fetch
> and had to add them ignore plugin

Can you explain what these errors were and show me what changes you made?

**Comment by varungupta85** [comment]
I was getting errors like these.
<pre>
ERROR in ./~/jsdom/~/tough-cookie/package.json
Module parse failed: D:\vgupta\experiments\react-testing-master\node_modules\jsd
om\node_modules\tough-cookie\package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "author": {
|     "name": "Jeremy Stashewsky",
|     "email": "jstashewsky@salesforce.com"
 @ ./~/jsdom/~/tough-cookie/lib/cookie.js 38:14-40

ERROR in ./~/jsdom/~/cssstyle/lib/CSSStyleDeclaration.js
Module not found: Error: Cannot resolve module 'fs' in D:\vgupta\experiments\rea
ct-testing-master\node_modules\jsdom\node_modules\cssstyle\lib
 @ ./~/jsdom/~/cssstyle/lib/CSSStyleDeclaration.js 7:9-22

ERROR in ./~/jsdom/lib/jsdom/web-idl/dom-exception-table.json
Module parse failed: D:\vgupta\experiments\react-testing-master\node_modules\jsd
om\lib\jsdom\web-idl\dom-exception-table.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "IndexSizeError": {
|     "description": "The index is not in the allowed range.",
|     "legacyCodeName": "INDEX_SIZE_ERR",
 @ ./~/jsdom/lib/jsdom/web-idl/DOMException.js 4:14-51
</pre>
There were quite a few others like these. I added below lines to the plugins section of the webpack.config.js file

<pre>
new webpack.IgnorePlugin(/jsdom$/),
new webpack.IgnorePlugin(/node-fetch$/)
</pre>

I think you have added a null-loader for jsdom and node-fetch in webpack config but for some reason, I was observing the above errors. After adding the above the lines, all the errors went away.

**Comment by robertknight** [comment]
I've updated master to work with the current versions of React, Babel and Webpack. I haven't yet tested it under Windows however.

**Comment by robertknight** [comment]
I've also replaced the custom `fetch()` wrapper with the better known [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) library which avoids pulling the server-side version into the webpack bundle.

**Comment by varungupta85** [comment]
Which URL do you hit to run the tests in the browser? I run webpack-dev-server and go to URL localhost:8080/tests/html but that doesn't run any tests on Windows. I am not sure if the tests will run in Linux but I doubt it as it should be independent of the OS.

**Comment by robertknight** [comment]
As per the instructions in the README, just open the tests.html file directly (ie. with a file:///) URL.
This is simple but for automation of tests in a CI environment, you'd do much better to use Karma with mocha. That unfortunately involves a bunch of extra configuration and tooling, but the result is that you can run the tests from the command-line easily.

**Comment by robertknight** [comment]
I'm closing this now per my previous comment. Please let me know if that doesn't help and I'll reopen this.
